[package]
name = "bevy_editor_pls_default_windows"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
viewport = []

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", default-features = false }
bevy_editor_pls_core = { path = "../bevy_editor_pls_core" }
bevy-inspector-egui = { git = "https://github.com/jakobhellermann/bevy-inspector-egui", branch = "bevy-main" }
bevy_mod_raycast = { git = "https://github.com/aevyrie/bevy_mod_raycast" }
indexmap = "1.7"
pretty-type-name = "1.0"
bevy_mod_debugdump = { git = "https://github.com/jakobhellermann/bevy_mod_debugdump", branch = "bevy-main" }
opener = "0.5.0"
